--
-- PostgreSQL database dump
--

\restrict 559NfsE7S1utmzvw9JYQUXN0bNJwLgfZRMbS4XWRSr4FC5ymx1QpLNONTEO4SJH

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2026-06-30 07:44:31

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 75932)
-- Name: Statuses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Statuses" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Statuses" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 75931)
-- Name: Statuses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Statuses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Statuses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 75948)
-- Name: Tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tasks" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Deadline" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "StatusId" integer NOT NULL,
    "UserId" integer
);


ALTER TABLE public."Tasks" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 75947)
-- Name: Tasks_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tasks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tasks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 75940)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Login" text NOT NULL,
    "Password" text NOT NULL,
    "Role" text NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 75939)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 75926)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4814 (class 0 OID 75932)
-- Dependencies: 219
-- Data for Name: Statuses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Statuses" ("Id", "Name") FROM stdin;
1	Новая
2	В работе
3	Завершена
4	Отменена
\.


--
-- TOC entry 4818 (class 0 OID 75948)
-- Dependencies: 223
-- Data for Name: Tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Tasks" ("Id", "Title", "Description", "Deadline", "CreatedAt", "StatusId", "UserId") FROM stdin;
6	сдать экзамен	получить удовлтворитльную оценку (3-4)	2026-06-30 03:00:00+03	2026-06-30 07:01:36.639963+03	2	1
8	поспать 8 часов		2026-07-01 03:00:00+03	2026-06-30 07:26:51.992204+03	1	3
7	что-то новое	поспать побольше	2026-06-30 03:00:00+03	2026-06-30 07:03:54.48424+03	3	3
\.


--
-- TOC entry 4816 (class 0 OID 75940)
-- Dependencies: 221
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Login", "Password", "Role") FROM stdin;
2	dovud	fcd06d2638c50b07cf801cbffa30639edd7b435af0efe9b340e2bb6dfa6b0bc5e2d5b35fa568b40f1c4a85f8fec0a2e85f972d8cf3922f449bc6adbc3515f2ce	User
1	admin	c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec	Admin
3	me	0dd3e512642c97ca3f747f9a76e374fbda73f9292823c0313be9d78add7cdd8f72235af0c553dd26797e78e1854edee0ae002f8aba074b066dfce1af114e32f8	User
4	you	2618aefa951451f6352a170e4da73ea458a6f602c7920c394e44d3ea21f60f64a8075a5a0b264e62eadb3a27aea273f457d6e06bcfc4c5eb9fdf837a0bdc2dca	User
\.


--
-- TOC entry 4812 (class 0 OID 75926)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260630013630_InitialCreate	8.0.26
\.


--
-- TOC entry 4824 (class 0 OID 0)
-- Dependencies: 218
-- Name: Statuses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Statuses_Id_seq"', 5, false);


--
-- TOC entry 4825 (class 0 OID 0)
-- Dependencies: 222
-- Name: Tasks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Tasks_Id_seq"', 8, true);


--
-- TOC entry 4826 (class 0 OID 0)
-- Dependencies: 220
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 4, true);


--
-- TOC entry 4658 (class 2606 OID 75938)
-- Name: Statuses PK_Statuses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Statuses"
    ADD CONSTRAINT "PK_Statuses" PRIMARY KEY ("Id");


--
-- TOC entry 4664 (class 2606 OID 75954)
-- Name: Tasks PK_Tasks; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id");


--
-- TOC entry 4660 (class 2606 OID 75946)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4656 (class 2606 OID 75930)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4661 (class 1259 OID 75965)
-- Name: IX_Tasks_StatusId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_StatusId" ON public."Tasks" USING btree ("StatusId");


--
-- TOC entry 4662 (class 1259 OID 75966)
-- Name: IX_Tasks_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_UserId" ON public."Tasks" USING btree ("UserId");


--
-- TOC entry 4665 (class 2606 OID 75955)
-- Name: Tasks FK_Tasks_Statuses_StatusId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES public."Statuses"("Id") ON DELETE CASCADE;


--
-- TOC entry 4666 (class 2606 OID 75960)
-- Name: Tasks FK_Tasks_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id");


-- Completed on 2026-06-30 07:44:32

--
-- PostgreSQL database dump complete
--

\unrestrict 559NfsE7S1utmzvw9JYQUXN0bNJwLgfZRMbS4XWRSr4FC5ymx1QpLNONTEO4SJH

